[package]
name        = "Flix-ANSI-Terminal"
description = "An API for ANSI terminal operations"
version     = "1.4.0"
flix        = "0.43.0"
license     = "Apache-2.0"
authors     = ["Jonathan Lindegaard Starup"]
